"""adding an attribute in comment table

Revision ID: 438fff51e9a5
Revises: a70903ce41a2
Create Date: 2019-03-02 17:00:00.865989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438fff51e9a5'
down_revision = 'a70903ce41a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('names', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_comments_names'), 'comments', ['names'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_names'), table_name='comments')
    op.drop_column('comments', 'names')
    # ### end Alembic commands ###
