"""Initial Migration

Revision ID: a8db2cc4d41a
Revises: 
Create Date: 2019-02-26 19:00:56.327272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8db2cc4d41a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitches_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('users_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'pitches', ['pitches_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['users_id'], ['id'])
    op.drop_constraint('pitches_users_id_fkey', 'pitches', type_='foreignkey')
    op.create_foreign_key(None, 'pitches', 'users', ['users_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.create_foreign_key('pitches_users_id_fkey', 'pitches', 'comments', ['users_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'users_id')
    op.drop_column('comments', 'pitches_id')
    # ### end Alembic commands ###
